
name: Github action for your deployment

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Create Dockerfile
          run: |
            echo "
                FROM rust:1 as build
                WORKDIR /app
                COPY . .
                RUN cargo build --release
                FROM ubuntu:latest
                WORKDIR /app
                RUN apt update
                COPY --from=build /app/target/release/hyp .
                RUN chmod +x ./hyp
                CMD ["./hyp"]
                " > Dockerfile

        - name: Build image from Dockerfile and push to patr-registry
          run: |
            docker login -u ashish-oli -p ${REGISTRY_PASSWORD} registry.patr.cloud
            docker build . -t ashish-oli/deployment
            docker tag ashish-oli/deployment registry.patr.cloud/personal-workspace-e883956e0ede454a8c06e7afe768de5f/rust:latest 
            docker push registry.patr.cloud/personal-workspace-e883956e0ede454a8c06e7afe768de5f/rust:latest
